In [1]:
from pathlib import Path
import pandas as pd

In [ ]:
main = Path("main_table.csv")
# main = Path("../../data/dept_manager.csv")\
main_df = pd.read_csv(main)
main_df.head()

  dept_no  emp_no
0    d001  110022
1    d001  110039
2    d002  110085
3    d002  110114
4    d003  110183

Question 3 table output

In [3]:
q3 = Path("Question_3_table.csv")
q3_df = pd.read_csv(q3)
q3_df.head()

     title dept_no        dept_name  emp_no     last_name first_name
0  Manager    d001        Marketing  110022    Markovitch  Margareta
1  Manager    d001        Marketing  110039      Minakawa   Vishwani
2  Manager    d002          Finance  110085         Alpin       Ebru
3  Manager    d002          Finance  110114    Legleitner      Isamu
4  Manager    d003  Human Resources  110183  Ossenbruggen    Shirish